image: sgrio/java-oracle:jdk_9

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build --stacktrace
  only:
    - master
  artifacts:
    paths:
    - build/libs/*.jar
    expire_in: 1 week

after_script:
- echo "End CI"
 
