image: openjdk:11

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    when: always
    paths:
    - build/reports/spotbugs/*.html
    - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

after_script:
- echo "End CI"
 
