status = WARN

appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss,SSS} [%-25t] %logger{36}%n%highlight{%5level} - %msg%ex%n

logger.dua3.name = com.dua3
logger.dua3.level = INFO

logger.top.name =
logger.top.level = WARN

rootLogger.level = INFO
rootLogger.appenderRef.console.ref = Console
