[release]
schemaVersion = 1
releaseType = "patch"
bomVersion = "24.4.1"
sourceRevision = "4dd5b090a308113f35a7689af423faca324cd526"

[modules.utility]
version = "24.4.1"
sourceRevision = "4dd5b090a308113f35a7689af423faca324cd526"
selected = true
reason = "direct source change"

[modules.utility-db]
version = "24.4.0"
sourceRevision = "0271b428bb4b9651e275b169024f436fc0621151"
selected = false
reason = "retained published module"

[modules.utility-swing]
version = "24.4.0"
sourceRevision = "0271b428bb4b9651e275b169024f436fc0621151"
selected = false
reason = "retained published module"

[modules.utility-fx]
version = "24.4.0"
sourceRevision = "0271b428bb4b9651e275b169024f436fc0621151"
selected = false
reason = "retained published module"

[modules.utility-fx-icons]
version = "24.4.1"
sourceRevision = "4dd5b090a308113f35a7689af423faca324cd526"
selected = true
reason = "direct source change"

[modules.utility-fx-icons-ikonli]
version = "24.4.0"
sourceRevision = "0271b428bb4b9651e275b169024f436fc0621151"
selected = false
reason = "retained published module"

[modules.utility-fx-controls]
version = "24.4.1"
sourceRevision = "4dd5b090a308113f35a7689af423faca324cd526"
selected = true
reason = "direct source change"

[modules.utility-fx-db]
version = "24.4.0"
sourceRevision = "0271b428bb4b9651e275b169024f436fc0621151"
selected = false
reason = "retained published module"

[modules.utility-fx-web]
version = "24.4.0"
sourceRevision = "0271b428bb4b9651e275b169024f436fc0621151"
selected = false
reason = "retained published module"
