[release]
schemaVersion = 2
bomVersion = "24.5.0"
publishedRevision = "1a80f9e99d619192c8121cbe91a3e2f3cdff1c05"

[modules.utility]
version = "24.5.0"
publishedRevision = "1a80f9e99d619192c8121cbe91a3e2f3cdff1c05"
paths = ["utility"]

[modules.utility-db]
version = "24.5.0"
publishedRevision = "1a80f9e99d619192c8121cbe91a3e2f3cdff1c05"
paths = ["utility-db"]

[modules.utility-swing]
version = "24.5.0"
publishedRevision = "1a80f9e99d619192c8121cbe91a3e2f3cdff1c05"
paths = ["utility-swing"]

[modules.utility-fx]
version = "24.5.0"
publishedRevision = "1a80f9e99d619192c8121cbe91a3e2f3cdff1c05"
paths = ["utility-fx"]

[modules.utility-fx-icons]
version = "24.5.0"
publishedRevision = "1a80f9e99d619192c8121cbe91a3e2f3cdff1c05"
paths = ["utility-fx-icons"]

[modules.utility-fx-icons-ikonli]
version = "24.5.0"
publishedRevision = "1a80f9e99d619192c8121cbe91a3e2f3cdff1c05"
paths = ["utility-fx-icons-ikonli"]

[modules.utility-fx-controls]
version = "24.5.0"
publishedRevision = "1a80f9e99d619192c8121cbe91a3e2f3cdff1c05"
paths = ["utility-fx-controls"]

[modules.utility-fx-db]
version = "24.5.0"
publishedRevision = "1a80f9e99d619192c8121cbe91a3e2f3cdff1c05"
paths = ["utility-fx-db"]

[modules.utility-fx-web]
version = "24.5.0"
publishedRevision = "1a80f9e99d619192c8121cbe91a3e2f3cdff1c05"
paths = ["utility-fx-web"]
