name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    outputs:
      compile_status: ${{ steps.compile.outputs.compile_status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute Gradle compile
        run: ./gradlew compileJava
        id: compile
        continue-on-error: false

  test:
    needs: compile
    runs-on: ubuntu-latest
    outputs:
      test_status: ${{ steps.test.outputs.test_status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: Execute Gradle test
        run: ./gradlew test
        id: test
        continue-on-error: false

  qodana:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      qodana_status: ${{ steps.qodana.outputs.qodana_status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: Qodana Scan
        id: qodana
        uses: JetBrains/qodana-action@v2023.3.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        continue-on-error: false
