name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload spotbugs report
        uses: actions/upload-artifact@v3
        with:
          path: spotbugs.xml

      - name: Set up badge for compile status
        run: echo "::set-output name=compile_status::success"
      - name: Set up badge for build status
        run: echo "::set-output name=build_status::success"

  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2.6
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: Set up badge for Qodana scan status
        run: echo "::set-output name=qodana_status::success"

  generate-badges:
    needs: [build, qodana]
    runs-on: ubuntu-latest
    steps:
      - name: Generate badges
        id: badges
        run: echo "::set-output name=compile_badge::https://img.shields.io/badge/compile-$((inputs.build.outputs.compile_status))-brightgreen.svg?style=flat-square && echo '::set-output name=build_badge::https://img.shields.io/badge/build-$((inputs.build.outputs.build_status))-yellow.svg?style=flat-square && echo '::set-output name=qodana_badge::https://img.shields.io/badge/Qodana-$((inputs.qodana.outputs.qodana_status))-orange.svg?style=flat-square"

  add-badges:
    needs: generate-badges
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/add-badges@v1
        with:
          shields: |
            ![Compile Status](${{needs.generate-badges.outputs.compile_badge}})
            ![Build Status](${{needs.generate-badges.outputs.build_badge}})
            ![Qodana Scan Status](${{needs.generate-badges.outputs.qodana_badge}})
